### PR TITLE
Change how latest api version is determined, fixes 1308

### LINKED ISSUE #1308: populate products ran in error
# Issue summary

flowing the `getting-started` in  `Start building your app` run `shopify populate products`, then error.

## Expected behavior

work well.

## Actual behavior

```
Please include this information in any issues/report along with relevant logs
/usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:138:in `block in fetch_api_version': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:139:in `fetch_api_version'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:117:in `api_client'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:42:in `block in query'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/util.rb:172:in `retry_after'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api.rb:43:in `query'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api/schema.rb:10:in `get'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api/populate_resource_command.rb:113:in `schema'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api/populate_resource_command.rb:102:in `input_options'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api/populate_resource_command.rb:33:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/admin_api/populate_resource_command.rb:17:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/command.rb:19:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:16:in `block (2 levels) in call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-ui/lib/cli/ui.rb:176:in `log_output_to'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:15:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/executor.rb:14:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/executor.rb:15:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:24:in `block in call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/monorail.rb:32:in `log'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/lib/shopify-cli/core/entry_point.rb:23:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:33:in `block in <top (required)>'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'
	from /usr/local/Cellar/shopify-cli/2.0.1/gems/shopify-cli-2.0.1/bin/shopify:32:in `<top (required)>'
	from /usr/local/bin/shopify:6:in `load'
	from /usr/local/bin/shopify:6:in `<main>'
```

## Steps to reproduce the problem

1. cd to dir
1. shopify login --STORE=XXXXX
1. shopify populate products

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

## Specifications

- App type:
- Operating System: osx
- Shell: zsh
- Ruby version (ruby -v): ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

### PR DESCRIPTION
**Pull request by mkevinosullivan**
### WHY are these changes introduced?

Fixes #1308

### WHAT is this pull request doing?

Previously, the latest API version was determined by looking for the displayName that had "Latest" in it - this only works when Partner account preferred language is English.
Now it's determined by reverse sorting the list of handles (ignoring "unstable") and picking the second on the list (the first will be the proposed version).

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).

### CODE REVIEW

File: lib/shopify-cli/admin_api.rb [hunk 1]
```diff
@@ -134,8 +134,12 @@ def fetch_api_version(ctx, api_version, shop)
...
         CLI::Kit::Util.begin do
           versions = client.query("api_versions")["data"]["publicApiVersions"]
-          latest = versions.find { |version| version["displayName"].include?("Latest") }
-          latest["handle"]
+          latest = versions
+            .select { |version| version["supported"] }
+            .map { |version| version["handle"] }
+            .sort
+            .reverse[0]
+          latest
```
Comment (paulomarg) [inline lib/shopify-cli/admin_api.rb:142]: Nit: we could simplify this a bit

```suggestion
          versions
            .select { |version| version["supported"] }
            .map { |version| version["handle"] }
            .sort
            .reverse[0]
```

**Review by paulomarg — APPROVED** [review]
🚀
