### PR TITLE
Fix `--ignore` flag issue when dealing with delayed json files on `shopify theme push`

### LINKED ISSUE #2454: [Bug]: `--ignore` flag doesn't do anything
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

When I run `shopify theme push --ignore config/settings_data.json` it should push everything except `settings_data.json`.

### Actual behavior

It pushes everything including `settings_data.json`.

### Stack trace

_No response_

### Reproduction steps

1. Use Shopify CLI to `pull` a theme.
2. In the Shopify dashboard, find the theme you just pulled _from_ (not your dev theme), click Customize and update some content.
3. Go back to Shopify CLI, run `shopify theme push --ignore config/settings_data.json`, select the theme from step 2. The content you just updated will be overwritten by whatever is in your local copy of `settings_data.json`.

I have tried `--ignore config/settings_data.json` with and without quotations and it makes no difference.

### Operating System

macOS Monterey v12.4

### CLI version (run `shopify version` if you're not sure)

2.20.0

### Shell

zsh

### Ruby version (run `ruby -v` if you're not sure)

3.1.2

### What language and version are you using in your application?

_No response_

### LINKED ISSUE #2455: [Enhancement]: please separate content (`settings_data.json`) from code
### What type of project(s) will this request affect?

theme

### Overview

This issue is probably bigger than the CLI. If there's somewhere else this should be posted I'd be happy to do so. I'll speak with anyone who will listen. 😅 

A lot of page content is stored in the theme via `settings_data.json`. This is a problem for a number of reasons.

- It's very easy to overwrite content without knowing it. Example: a dev pulls a theme to work on it, meanwhile the store owner updates some content, the dev finishes his work and pushes, the updated content reverts back to what it was before.
- If a dev is frequently working on a theme, it's annoying to have to pull the theme just in case someone changed something.
- If a theme is used on multiple stores with different content, deploying code updates is kind of a nightmare.

I know there is the `--ignore` flag for the `push` command, but that's not very robust. I just discovered that this flag mysteriously stopped working for me a while back. There was no warning and I have no way of knowing when it stopped, so I don't even know what content is now outdated without combing through the site.

Maybe I'm missing something, and if someone can explain why things were set up this way that would be great. But it just seems like separating content from code would solve a lot of problems here.

### Motivation

- It's very easy to overwrite content without knowing it. Example: a dev pulls a theme to work on it, meanwhile the store owner updates some content, the dev finishes his work and pushes, the updated content reverts back to what it was before.
- If a dev is frequently working on a theme, it's annoying to have to pull the theme just in case someone changed something.
- If a theme is used on multiple stores with different content, deploying code updates is kind of a nightmare.

I know there is the `--ignore` flag for the `push` command, but that's not very robust. I just discovered that this flag mysteriously stopped working for me a while back. There was no warning and I have no way of knowing when it stopped, so I don't even know what content is now outdated without combing through the site.

### PR DESCRIPTION
**Pull request by ulgut**
### WHY are these changes introduced?

Fixes [#2455](https://github.com/Shopify/shopify-cli/issues/2455)
Fixes [#2454](https://github.com/Shopify/shopify-cli/issues/2454)

`shopify theme push --ignore *.json` will not work properly (w or w/o stable flag). The ignore flag still works properly for non-json files

### WHAT is this pull request doing?

Allows `.json` files to be ignored again.

### How to test your changes?

1. Run `shopify theme pull` in a theme directory of your choice
2. Modify an asset file (`.js/.css`), `.liquid` file, and a `.json` file locally.
3. Run `shopify theme push --ignore [asset filename] [liquid filename] [json filename]` and note that the json file is not ignored.
4. Checkout `bulk-maintenance` branch.
5. Repeat 1-3 and notice that json file is ignored.

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above (if needed).

### CODE REVIEW

File: lib/shopify_cli/theme/syncer/json_update_handler.rb [hunk 1]
```diff
@@ -86,6 +86,10 @@ def delete_locally(file)
         def ask_update_strategy(file)
           Forms::SelectUpdateStrategy.ask(@ctx, [], file: file, exists_remotely: file_exist_remotely?(file)).strategy
         end
+
+        def ready_to_update(file)
```
Comment (karreiro) [inline lib/shopify_cli/theme/syncer/json_update_handler.rb:90]: I believe we could include the `?` suffix that boolean methods generally have.

Also, I'm wondering if we should call the method `ready_to_update?` or `updatable?`, as the ready may suggest we're waiting for something. Wdyt?

**Review by karreiro — COMMENTED** [review]
Thank you, @jessetuglu! Great stuff!

I believe we may include a unit test for the `enqueue_delayed_files_updates` method and then we'll be ready to merge it :)

(also, I've included a minor comment regarding the name of the method)

Thanks again for this PR!

**Review by karreiro — APPROVED** [review]
Awesome 🔥
