### PR TITLE
Fix theme app extension hot reload to work with added/deleted assets

### LINKED ISSUE #2586: [Bub] TAE: The page is not updated when an asset is added/deleted
### Description

- When users delete an asset, they need to modify a liquid file to force a sync, and refresh the page
  - [steps to reproduce here](https://drive.google.com/file/d/1SyKphFwBUyczHfo1ISarKKhAleH71k9z/view?usp=sharing)

- When users add an asset, they need refresh the page 
   - [steps to reproduce here](https://drive.google.com/file/d/1OzOJjfujHdEdHgv2Yzju7X9xexc2oQe5/view?usp=sharing)

### Proposal to solve

For solving this issue, we will need to introduce force the sync [1] when an asset is deleted and added. Also, we will need to trigger an event to refresh the page when this special sync is concluded.

[1] In this context, forcing means skipping these conditions: https://github.com/Shopify/shopify-cli/blob/main-extension-serve/lib/shopify_cli/theme/extension/syncer/extension_serve_job.rb#L33-L34

### PR DESCRIPTION
**Pull request by karreiro**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/shopify-cli/issues/2586.

Now, when a file gets created or deleted, the CLI waits for the upload of the theme app extension and refreshes the browser. In both scenarios, we can't patch theme extension rendering at SFR level, as they don't exist remotely.

### WHAT is this pull request doing?

This PR introduces blocking operations in the `FileChangeHook` and in the `Syncer`. In the `FileChangeHook` side, blocking operations hold the broadcast events until the extension gets uploaded. In the `Syncer` side, blocking operations are not throttled by the  `ExtensionServeJob`, as we need to upload the extension immediately to refresh the browser. 

### How to test your changes?

- Run `shopify-dev extension serve`
- Remove a file
- Notice the browser is refreshed
- Add a file
- Notice the browser is refreshed

demo

### Post-release steps

None.

### Update checklist

- [x] ([N/A](https://github.com/Shopify/shopify-cli/pull/2577)) I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above (if needed).

### CODE REVIEW

File: lib/shopify_cli/theme/extension/dev_server/hooks/file_change_hook.rb [hunk 1]
```diff
@@ -6,34 +6,59 @@ module Extension
...
-                .map { |f| @extension[f] }
-                .reject(&:liquid_css?)
-              deleted_files = removed
-                .map { |f| @extension[f] }
 
-              reload_page(removed) unless deleted_files.empty?
-              hot_reload(files) unless files.empty?
+              modified = paths(modified).select { |file| @extension.extension_file?(file) }
+              added = paths(added).select { |file| @extension.extension_file?(file) }
+              removed = paths(removed)
```
Comment (mgmanzella) [inline lib/shopify_cli/theme/extension/dev_server/hooks/file_change_hook.rb:22]: in theory could we check if the removed file are extension files by comparing the extension root with the removed file root?

File: lib/shopify_cli/theme/extension/syncer.rb [hunk 2]
```diff
@@ -15,15 +18,24 @@ def initialize(ctx, extension:, project:, specification_handler:)
           @specification_handler = specification_handler
 
           @pool = ThreadPool.new(pool_size: 1)
-          @pending_updates = extension.extension_files
-          @update_mutex = Mutex.new
+          @pending_operations = extension.extension_files.map { |file| Operation.new(file, :update) }
```
Comment (mgmanzella) [inline lib/shopify_cli/theme/extension/syncer.rb:21]: 🔥 love the new `Operation` struct

**Review by mgmanzella — APPROVED** [review]
noice!! testing looked great 🚀

File: lib/shopify_cli/theme/extension/dev_server/hooks/file_change_hook.rb (hunk 1 above)
Comment (karreiro) [reply lib/shopify_cli/theme/extension/dev_server/hooks/file_change_hook.rb:22]: I believe that check would always return true as the [`FileSystemListener`](https://github.com/Shopify/shopify-cli/blob/fix-2586/lib/shopify_cli/theme/extension/dev_server/watcher.rb#L21) triggers events based on the extension root. I'm not sure if I'm missing something tho, please let me know :)

(I will proceed with the merge, but I can apply that enhancement in a new PR if I missed something)

Thanks for the comment, @mgmanzella! :)
