### PR TITLE
Provide better DX when dealing with empty theme selection

### LINKED ISSUE #2327: [Bug]: ArgumentError: insufficient options
### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

it should have worked

### Actual behavior

It didn't work

### Stack trace

```shell
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:192:in `ask_interactive'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/vendor/deps/cli-ui/lib/cli/ui/prompt.rb:100:in `ask'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/project_types/theme/forms/select.rb:12:in `ask'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/shopify_cli/form.rb:13:in `ask'
/home/mark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify-cli-2.17.0/lib/project_types/theme/commands/publish.rb:17:in `call'
```

### Reproduction steps

1. push success
2. publish failure

### Operating System

x86_64-linux

### CLI version (run `shopify version` if you're not sure)

2.17.0

### Shell

/bin/bash

### Ruby version (run `ruby -v` if you're not sure)

3.1.2

### What language and version are you using in your application?

Ruby 3.1.2, Node 17.9, PHP 8.1.2

### PR DESCRIPTION
**Pull request by ulgut**
### WHY are these changes introduced?

Fixes [#2327](https://github.com/Shopify/shopify-cli/issues/2327)

Fixes known cases where developers would go to select a theme from a dropdown and a nasty error was thrown. 
Known cases:
1. When running `theme publish` on a store with no unpublished themes.
2. When running `theme delete` on a store with no other non-live themes.

### WHAT is this pull request doing?

See the linked issue for the before error.
Now, the user sees: 
screen_shot_2022-05-25_at_12 45 41_pm
### How to test your changes?

1. Run `shopify theme publish` on a store with no unpublished themes.
2. Run `shopify theme delete` on a store with no other non-live themes.
### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above (if needed).

### CODE REVIEW

File: test/project_types/theme/commands/publish_test.rb [hunk 1]
```diff
@@ -78,6 +78,16 @@ def test_publish_select_aborting
 
         @command.call([])
       end
+
+      def test_publish_when_no_valid_themes_to_select_from
```
Comment (jessetuglu) [inline test/project_types/theme/commands/publish_test.rb:82]: this should be testing when there is no theme available for publishing

File: lib/project_types/theme/messages/messages.rb [hunk 2]
```diff
@@ -42,6 +42,8 @@ module Messages
           HELP
           done: "Your theme is now live at %s",
           not_found: "Theme #%s does not exist",
+          no_themes_error: "No valid, publishable themes available.",
+          no_themes_resolution: "Do you have any unpublished themes?",
```
Comment (karreiro) [inline lib/project_types/theme/messages/messages.rb:46]:
```suggestion
          no_themes_error: "You don't have any theme to be published.",
          no_themes_resolution: "Try to create an unpublished theme with {{command:theme push -u -t <theme_name>}}.",
```

File: lib/project_types/theme/messages/messages.rb [hunk 3]
```diff
@@ -233,6 +235,8 @@ module Messages
           HELP
           select: "Select theme to delete",
           done: "%s theme(s) deleted",
+          no_themes_error: "No themes to delete.",
+          no_themes_resolution: "Do you have any non-live themes?",
```
Comment (karreiro) [inline lib/project_types/theme/messages/messages.rb:239]:
```suggestion
          no_themes_error: "You don't have any theme to be deleted.",
          no_themes_resolution: "Try to create an unpublished theme with {{command:theme push -u -t <theme_name>}}.",
```

**Review by karreiro — COMMENTED** [review]
Great stuff, @jessetuglu! 🚀 Thank you!

I've left just two minor comments about the error messages. Generally, I believe that it's a good approach to give a clear suggestion in the "try-this" context, but please, let me know wdyt about the new messages :)

File: lib/project_types/theme/messages/messages.rb (hunk 3 above)
Comment (jessetuglu) [reply lib/project_types/theme/messages/messages.rb:239]: This looks like the same `no_themes_resolution` message as the `publish` one?

Comment (jessetuglu) [reply lib/project_types/theme/messages/messages.rb:239]: This is the same message as above – do we want to specify that you need an unpublished theme to `delete`?

Comment (karreiro) [reply lib/project_types/theme/messages/messages.rb]: Considering the other theme types (development/demo/live) and their purposes, I believe it's a fair suggestion. So, developers may be aware they can manage (create/delete) unpublished themes.

**Review by karreiro — APPROVED** [review]
Thank you, @jessetuglu! 🚀
