### PR TITLE
Fix for Windows start command, issue 1294

### LINKED ISSUE #1294: Unable to login through the CLI
The CLI will not work on my system after updating to 2.0.0 after problems with 1.14.0 this past weekend. I have upcoming deadlines and have been trying to create and start developing a new iteration of an older app for my company.
Currently, I am unable to use shopify create, shopify serve, or almost any of the other commands.

Here are the command line errors I receive while working from VS Code's terminal and their inputs.

PS C:\Users\jacob\Desktop\test> shopify whoami
It doesn't appear that you're logged in. You must log into a partner organization or a store staff account.

If trying to log into a store staff account, please use shopify login --store=STORE to log in.

PS C:\Users\jacob\Desktop\test> shopify login --store=jacobs-development-store.myshopify.com
'scope' is not recognized as an internal or external command,       
operable program or batch file.
'redirect_uri' is not recognized as an internal or external command,
operable program or batch file.
'state' is not recognized as an internal or external command,       
operable program or batch file.
'response_type' is not recognized as an internal or external command,
operable program or batch file.
'code_challenge' is not recognized as an internal or external command,
operable program or batch file.
'code_challenge_method' is not recognized as an internal or external command,
operable program or batch file.
X System call failed: start https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=9632a5b92148ea5ec1fce388e089307bae554ba71de6a4411da8103425d2&response_type=code&code_challenge=7PgYfFhzWE1AHqQqkj0nNVhAWRcdbezYBGZZ6P-2Bcs&code_challenge_method=S256

PS C:\Users\jacob\Desktop\test> shopify node create
X Please ensure you've logged in with shopify login and try again

PS C:\Users\jacob\Desktop\test> shopify whoami
Logged into store jacobs-development-store.myshopify.com as staff (no partner organizations available for this login)

-----------------------------------------------------------------

On opening of the link in the error, this error is displayed:
An error occured
invalid_request
The error was: 'response_type' required.
Request ID: 23483ae3aae2c65c73542bfa48d859a8

-----------------------------------------------------------------

Gem: 3.1.6
Ruby 2.7.3
Node: 14.17.1
Shopify-CLI: 2.0

### PR DESCRIPTION
**Pull request by mkevinosullivan**
### WHY are these changes introduced?

Fixes #1294

### WHAT is this pull request doing?

The `shopify login` command attempts to open the authentication URL in users default browser, using `start` command on Windows.  However, the `start` command doesn't accept URLs with special characters (e.g., query parameters) as the first argument - needs to be called using `start "" "url"`

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [x] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).

### CODE REVIEW

**Comment by DeepakR-28** [comment]
Windows. However, the `start` command doesn't accept URLs with special characters (e.g., query parameters) as the first argument - needs to be called using `start "" "url"`


it take me to shopify login page but then it shows 127.0.0.1 refused to connect

i tried to run it like this with quotes

` start "https://accounts.shopify.com/oauth/authorize?client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&scope=openid+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&redirect_uri=http%3A%2F%2F127.0.0.1%3A3456&state=0fd215ce90320c3b3024f7d62249a02ce115ba2ee83721b2ae74182445c9&response_type=code&code_challenge=YRj6kP1OFYQj5-uCyRGRtaUk6PYKHLvhivD2c879LmY&code_challenge_method=S256" `

File: lib/shopify-cli/context.rb [hunk 1]
```diff
@@ -327,7 +327,7 @@ def open_browser_url!(uri)
         if linux? && which("xdg-open")
           system("xdg-open", uri.to_s)
         elsif windows?
-          system("start", uri.to_s)
+          system("start \"\" \"#{uri}\"")
```
Comment (catlee) [inline lib/shopify-cli/context.rb:330]: did you try `system("start", "", uri.to_s)`?

Comment (catlee) [reply lib/shopify-cli/context.rb:330]: wow, bizarre!

**Review by catlee — APPROVED** [review]
