### PR TITLE
Fix for "X zip is required for packaging a theme" on Windows

### LINKED ISSUE #2513: [Bug]: X zip is required for packaging a theme. Please install zip using the appropriate package manager for your system.
### Please confirm that you:

- [X] Are working with Shopify CLI 2.0, not 3.0. (You can [open a 3.0 issue here](https://github.com/Shopify/cli/issues/new/choose).)
- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli/releases).

### What type of project are you working on?

theme

### Expected behavior

I am getting error when running the comman "shopify theme package" ->  X zip is required for packaging a theme. Please install zip using the appropriate package manager for your system.
However, I have tried installing Winzip and 7-Zip software, but the problem still persist:

### Actual behavior

image

### Stack trace

_No response_

### Reproduction steps

1, shopify theme package
2, error

### Operating System

Window 7

### CLI version (run `shopify version` if you're not sure)

2.18.1

### Shell

command prompt

### Ruby version (run `ruby -v` if you're not sure)

3.1.2p20

### What language and version are you using in your application?

Ruby 3.1.2p20,Node 10.13.0

### PR DESCRIPTION
**Pull request by mgmanzella**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/shopify-cli/issues/2513

### WHAT is this pull request doing?

Modifies the package command to use a 7zip to zip files when `theme package` is run on Windows

#### Machine Setup
The test steps should be run on all platforms. 

##### Mac
- Clone shopify-cli repo
- Add the following to ~/.zshrc and replace <USERNAME> with your machine username:
```
alias shopify-dev="/Users/<USERNAME>/src/github.com/Shopify/shopify-cli/bin/shopify"
```

##### Windows
- Clone shopify-cli repo and checkout branch with changes
- Change `shopify.bat` name in the bin folder of the repo to `shopify-dev.bat`
- Add the bin folder to the PATH 
- Restart machine
- Confirm setup works by running shopify-dev version

##### Linux

TODO

#### Test Steps 

1. If you don't have a theme available, `shopify-dev theme init`
2. `shopify-dev theme package <path/to/theme>`
3. Confirm zip file is generated in theme directory with theme name and version as the name
4. Unzip the zip file and confirm only directories in [THEME_DIRECTORIES](https://github.com/Shopify/shopify-cli/blob/13990c80751bf0bd301024dc5968b6ccbfedefad/lib/project_types/theme/commands/package.rb#L10-L19) are present
5. Confirm nested folders were also included 
6. `cd <theme-name>`
7. `shopify-dev theme package`
8. Repeat steps 3-5

### Post-release steps

- Open issue in shopify-dev to update theme package docs to indicate we only support `7zip` for theme package on windows

### Update checklist

- [x] I've added a CHANGELOG entry for this PR (if the change is public-facing)
- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows).
- [x] I've left the version number as is (we'll handle incrementing this when releasing).
- [x] I've included any post-release steps in the section above (if needed).

### CODE REVIEW

**Review by karreiro — COMMENTED** [review]
Great stuff, @mgmanzella! 🚀 LGTM and works on Windows as well :)

What do you think about handling `7z` as a fallback of the `zip` command?

Some Linux distributions might not have the `zip` command, but they may have `7z`, so we'd cover this case.

Thank you for this PR!

File: lib/project_types/theme/commands/package.rb [hunk 1]
```diff
@@ -18,11 +18,15 @@ class Package < ShopifyCLI::Command::SubCommand
         release-notes.md
       ]
 
+      ZIP = "zip"
+      SEVEN_ZIP = "7z"
```
Comment (mgmanzella) [inline lib/project_types/theme/commands/package.rb:22]: how do we feel about using `SEVEN` cause a number can't be the first letter of the variable name?

File: lib/project_types/theme/commands/package.rb [hunk 2]
```diff
@@ -53,6 +56,18 @@ def theme_name(path)
 
         [theme_name, theme_info["theme_version"]].compact.join("-")
       end
+
+      def command
+        @command ||= if @ctx.which(ZIP) == true
+          ZIP
+        elsif @ctx.which(SEVEN_ZIP) == true
+          SEVEN_ZIP
+        end
```
Comment (mgmanzella) [inline lib/project_types/theme/commands/package.rb]: soooo originally i had this:
```
@command ||= (if @ctx.which(ZIP) == true
  ZIP
elsif @ctx.which(SEVEN_ZIP) == true
  SEVEN_ZIP
end)
```

but this was not rubocop friendly. without the parentheses, the `||=` statement doesn't work as it should and it evaluates the if statement over and over again. im not sure why?

File: lib/project_types/theme/commands/package.rb [hunk 3]
```diff
@@ -53,6 +56,20 @@ def theme_name(path)
...
+
+      def command
+        return @command unless @command.nil?
+
+        @command = if @ctx.which(ZIP) == true
+          ZIP
+        elsif @ctx.which(SEVEN_ZIP) == true
+          SEVEN_ZIP
+        end
+      end
```
Comment (mgmanzella) [inline lib/project_types/theme/commands/package.rb:68]: so originally this method looked like this:
```
def command
  @command ||= (if @ctx.which(ZIP) == true
    ZIP
  elsif @ctx.which(SEVEN_ZIP) == true
    SEVEN_ZIP
  end)
end
```
however rubocop kept removing the parentheses. these were necessary because `||=` wasn't working as expected without the parentheses and evaluated the if statement even when `@command` was set. 

so! let me know if you hate this and want me to try something else

File: lib/project_types/theme/messages/messages.rb [hunk 4]
```diff
@@ -302,8 +302,8 @@ module Messages
             Usage: {{command:%s theme package [ ROOT ]}}
           HELP
           error: {
-            prereq_command_required: "%1$s is required for packaging a theme. Please install %1$s "\
-              "using the appropriate package manager for your system.",
+            prereq_command_required: "zip or 7zip is required for packaging a theme. Please install "\
+              "zip or 7zip using the appropriate package manager for your system.",
             missing_config: "Provide a config/settings_schema.json to package your theme",
```
Comment (mgmanzella) [inline lib/project_types/theme/messages/messages.rb:307]: how do we feel about hardcoding `zip or 7zip` here?

**Review by mgmanzella — COMMENTED** [review]
> What do you think about handling 7z as a fallback of the zip command?

great idea!! @karreiro i made changes to do this and left some comments for you to look at 🙏

File: lib/project_types/theme/commands/package.rb (hunk 1 above)
Comment (karreiro) [reply lib/project_types/theme/commands/package.rb:22]: +1 from my side :)

File: lib/project_types/theme/commands/package.rb (hunk 3 above)
Comment (karreiro) [inline lib/project_types/theme/commands/package.rb:68]: The `which` method returns the path the command (e.g., @ctx.which(ZIP) returns `"/usr/bin/zip"` on my machine. So, we may change this method to something like this:

```suggestion
      def command
        return @command unless @command.nil?

        @command = if @ctx.which(ZIP)
          ZIP
        elsif @ctx.which(SEVEN_ZIP)
          SEVEN_ZIP
        end
      end
```

**Review by karreiro — COMMENTED** [review]
Thank you for the updates, @mgmanzella!

I've added a minor comment about the `which` method :)

File: lib/project_types/theme/commands/package.rb [hunk 5]
```diff
@@ -53,6 +56,18 @@ def theme_name(path)
...
         [theme_name, theme_info["theme_version"]].compact.join("-")
       end
+
+      def command
+        @command ||= if @ctx.which(ZIP)
+          ZIP
+        elsif @ctx.which(SEVEN_ZIP)
+          SEVEN_ZIP
+        end
+      end
```
Comment (mgmanzella) [inline lib/project_types/theme/commands/package.rb:66]: tried using a case statement here but rubocop was complaining about an empty case

**Review by karreiro — APPROVED** [review]
Thanks a lot, @mgmanzella! LGMT and works greatly too!
